import type { AuthProfile, IR } from "@loadam/core";

export interface CompileContractOptions {
  /** Override the base URL inferred from IR.servers[0]. */
  baseUrl?: string;
  /** Path the spec will be copied to in the output dir. Default `openapi.yaml`. */
  specFileName?: string;
  /** Hypothesis examples per operation. Default 25. */
  examples?: number;
}

export interface CompileContractResult {
  /** Map of relative file path → file contents. */
  files: Record<string, string>;
  /** Required env vars (for .env.example). */
  envVars: string[];
}

/**
 * Compile an IR into a runnable Schemathesis project.
 *
 * Schemathesis is a Python library that fuzzes an API against its OpenAPI
 * spec — for each operation it derives Hypothesis strategies from the
 * declared schemas, sends randomized requests, and asserts the response
 * conforms. Catches the bugs unit tests don't, without you writing them.
 *
 * The emitted project is a small `pytest` project. Users run it with
 * `pip install -e .` then `pytest`. Spec is copied next to the tests so
 * the project is self-contained and CI-friendly.
 */
export function compileContract(
  ir: IR,
  specSource: string,
  opts: CompileContractOptions = {},
): CompileContractResult {
  const specFileName = opts.specFileName ?? "openapi.yaml";
  const baseUrl = opts.baseUrl ?? ir.servers[0]?.url ?? "http://localhost:4010";
  const examples = opts.examples ?? 25;
  const envVars = collectEnvVars(ir.auth);

  const files: Record<string, string> = {
    [specFileName]: specSource.endsWith("\n") ? specSource : `${specSource}\n`,
    "pyproject.toml": emitPyProject(ir),
    "conftest.py": emitConftest(ir, specFileName, baseUrl, envVars),
    "test_contract.py": emitContractTests(ir, examples),
    "README.md": emitReadme(ir, specFileName),
    ".env.example": emitEnvExample(baseUrl, envVars),
  };

  return { files, envVars };
}

function collectEnvVars(profiles: AuthProfile[]): string[] {
  const out = new Set<string>();
  for (const p of profiles) {
    switch (p.kind) {
      case "bearer":
        out.add(p.tokenEnv ?? "API_TOKEN");
        break;
      case "apiKey":
        out.add(p.valueEnv ?? p.name.toUpperCase().replace(/[^A-Z0-9]/g, "_"));
        break;
      case "basic":
        out.add(p.userEnv ?? "API_USER");
        out.add(p.passEnv ?? "API_PASS");
        break;
      case "oauth2_cc":
        out.add(p.clientIdEnv);
        out.add(p.clientSecretEnv);
        break;
    }
  }
  return [...out].sort();
}

function emitPyProject(ir: IR): string {
  const name = slugify(ir.meta.title) || "loadam-contract";
  return `[project]
name = "${name}-contract"
version = "0.0.0"
description = "Schemathesis contract suite for ${ir.meta.title} — generated by loadam"
requires-python = ">=3.10"
dependencies = [
  "schemathesis>=3.36",
  "pytest>=8.0",
  "pyyaml>=6.0",
  "python-dotenv>=1.0",
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["."]
`;
}

function emitConftest(ir: IR, specFileName: string, baseUrl: string, envVars: string[]): string {
  const authBuilder = emitAuthBuilder(ir.auth);
  return `# AUTO-GENERATED by @loadam/test-contract
"""
Shared fixtures for the Schemathesis contract suite.

The schema is loaded from a checked-in copy of the spec so the suite is
self-contained and reproducible. Override BASE_URL / credentials via env vars.
"""

import os
from pathlib import Path

import schemathesis
from dotenv import load_dotenv

load_dotenv()

SPEC_PATH = Path(__file__).parent / "${specFileName}"
BASE_URL = os.getenv("BASE_URL", ${JSON.stringify(baseUrl)})

# Required env vars — listed for ergonomic discovery; not hard-required
# (Schemathesis can still run unauth flows).
REQUIRED_ENV = ${JSON.stringify(envVars)}

schema = schemathesis.from_path(str(SPEC_PATH), base_url=BASE_URL)


def auth_kwargs() -> dict:
${authBuilder}
`;
}

function emitAuthBuilder(profiles: AuthProfile[]): string {
  if (profiles.length === 0) {
    return "    return {}\n";
  }
  const lines: string[] = ["    headers: dict = {}", "    params: dict = {}"];
  for (const p of profiles) {
    switch (p.kind) {
      case "bearer": {
        const env = p.tokenEnv ?? "API_TOKEN";
        lines.push(`    if os.getenv(${JSON.stringify(env)}):`);
        lines.push(
          `        headers["Authorization"] = f"Bearer {os.environ[${JSON.stringify(env)}]}"`,
        );
        break;
      }
      case "apiKey": {
        const env = p.valueEnv ?? p.name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
        if (p.in === "header") {
          lines.push(`    if os.getenv(${JSON.stringify(env)}):`);
          lines.push(
            `        headers[${JSON.stringify(p.name)}] = os.environ[${JSON.stringify(env)}]`,
          );
        } else if (p.in === "query") {
          lines.push(`    if os.getenv(${JSON.stringify(env)}):`);
          lines.push(
            `        params[${JSON.stringify(p.name)}] = os.environ[${JSON.stringify(env)}]`,
          );
        }
        break;
      }
      case "basic": {
        const u = p.userEnv ?? "API_USER";
        const pw = p.passEnv ?? "API_PASS";
        lines.push(`    if os.getenv(${JSON.stringify(u)}) and os.getenv(${JSON.stringify(pw)}):`);
        lines.push(
          `        import base64; headers["Authorization"] = "Basic " + base64.b64encode(f"{os.environ[${JSON.stringify(u)}]}:{os.environ[${JSON.stringify(pw)}]}".encode()).decode()`,
        );
        break;
      }
    }
  }
  lines.push(`    return {"headers": headers, "params": params}`);
  return `${lines.join("\n")}\n`;
}

function emitContractTests(_ir: IR, examples: number): string {
  return `# AUTO-GENERATED by @loadam/test-contract
"""
Property-based contract tests for every declared operation.

Each operation is fuzzed ~${examples} times. Schemathesis asserts:
  - response status is one of the declared statuses
  - response body validates against the declared response schema
  - server returns no 500s on valid inputs

Mutating endpoints (POST/PUT/PATCH/DELETE) are included by default — point
the suite at a disposable / sandbox environment, not production.
"""

from hypothesis import settings

from conftest import auth_kwargs, schema

import schemathesis


@schema.parametrize()
@settings(max_examples=${examples}, deadline=None)
def test_contract(case: "schemathesis.Case") -> None:
    response = case.call(**auth_kwargs())
    case.validate_response(response)
`;
}

function emitReadme(ir: IR, specFileName: string): string {
  return `# ${ir.meta.title} — contract test suite

Generated by [loadam](https://github.com/loadam) from your API spec.

## Run

\`\`\`bash
# 1. install
python -m venv .venv && source .venv/bin/activate
pip install -e .

# 2. fill credentials (optional — Schemathesis runs unauth flows too)
cp .env.example .env

# 3. run
pytest
\`\`\`

## What's in here

- \`${specFileName}\` — checked-in copy of the spec under test.
- \`conftest.py\` — schema loader + auth builder.
- \`test_contract.py\` — Schemathesis property-based suite.

## Why contract tests?

For each operation, [Schemathesis](https://schemathesis.readthedocs.io/) derives
Hypothesis strategies from the declared schemas, sends randomised requests, and
asserts the responses conform. It catches the long tail of "we didn't validate
this combination" bugs unit tests miss.

## Regenerating

Re-run \`loadam contract\` to refresh. Edits to generated files will be overwritten.
`;
}

function emitEnvExample(baseUrl: string, envVars: string[]): string {
  const lines = ["# Generated by loadam — copy to .env and fill in.", `BASE_URL=${baseUrl}`, ""];
  for (const v of envVars) lines.push(`${v}=`);
  return `${lines.join("\n")}\n`;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
