import type { IR, Operation } from "@loadam/core";
import type { AuthEmission } from "./auth.js";
import { defaultBaseUrl } from "./sequence.js";

/**
 * String templates for the runtime k6 scripts. Plain template literals beat
 * a template engine for code we want diff-readable in PR review.
 *
 * k6 constraints:
 *   - Goja runtime: only k6/* imports work (no npm)
 *   - SharedArray for fixture data (memory-shared across VUs)
 *   - All credentials via __ENV.* (never inlined)
 *
 * Files we emit:
 *   config.js     — base URL, auth headers, URL builder
 *   flow.js       — exports `runFlow(iter)` shared by smoke + load
 *   smoke.js      — 1 VU × 1 iter
 *   load.js       — ramping stages
 *   fixtures.json — pre-generated body / path / query values
 *   package.json + README + .env.example
 */

export interface TemplateContext {
  ir: IR;
  baseUrl: string;
  sequencedOps: Operation[];
  auth: AuthEmission;
}

export function emitConfigJs(ctx: TemplateContext): string {
  const { auth } = ctx;
  const base = ctx.baseUrl;
  const headerEntries = Object.entries(auth.headers);
  const queryEntries = Object.entries(auth.query);

  const needsB64 = headerEntries.some(([, v]) => v.startsWith("__BASIC__:"));
  const importLine = needsB64 ? "import encoding from 'k6/encoding';\n" : "";

  const headersBody = headerEntries.length
    ? headerEntries.map(([k, v]) => `  ${buildHeaderLine(k, v)}`).join("\n")
    : "  // no auth headers";

  const queryBody = queryEntries.length
    ? queryEntries.map(([k, v]) => `    ${JSON.stringify(k)}: ${interpolate(v)},`).join("\n")
    : "";

  return `// AUTO-GENERATED by @loadam/test-k6
${importLine}
const BASE_URL = (typeof __ENV !== 'undefined' && __ENV.BASE_URL) || ${JSON.stringify(base)};

export function baseUrl() {
  return BASE_URL;
}

export function authHeaders() {
  const h = {};
${headersBody}
  return h;
}

export function authQuery() {
  return {
${queryBody}
  };
}

export function buildUrl(path, pathParams, queryParams) {
  let p = path;
  if (pathParams) {
    for (const k in pathParams) {
      if (pathParams[k] === undefined || pathParams[k] === null) continue;
      p = p.split('{' + k + '}').join(encodeURIComponent(String(pathParams[k])));
    }
  }
  const aq = authQuery();
  const merged = Object.assign({}, queryParams || {}, aq);
  const qs = Object.keys(merged)
    .filter((k) => merged[k] !== undefined && merged[k] !== null && merged[k] !== '')
    .map((k) => encodeURIComponent(k) + '=' + encodeURIComponent(String(merged[k])))
    .join('&');
  return BASE_URL + p + (qs ? '?' + qs : '');
}
`;
}

function buildHeaderLine(name: string, value: string): string {
  if (value.startsWith("__BASIC__:")) {
    const [, userEnv, passEnv] = value.split(":");
    return `if (__ENV.${userEnv} && __ENV.${passEnv}) { h.Authorization = 'Basic ' + encoding.b64encode(__ENV.${userEnv} + ':' + __ENV.${passEnv}); }`;
  }
  return `h[${JSON.stringify(name)}] = ${interpolate(value)};`;
}

function interpolate(value: string): string {
  const replaced = value.replace(/\$\{([A-Z0-9_]+)\}/g, (_m, name) => `\${__ENV.${name} || ''}`);
  return `\`${replaced}\``;
}

export function emitFlowJs(ctx: TemplateContext): string {
  const ops = ctx.sequencedOps;
  const lines: string[] = [];
  for (let i = 0; i < ops.length; i++) {
    const op = ops[i];
    if (!op) continue;
    lines.push(emitOpCall(op, i));
  }

  return `// AUTO-GENERATED by @loadam/test-k6
import http from 'k6/http';
import { check } from 'k6';
import { Counter, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';
import { authHeaders, buildUrl } from './config.js';

const opLatency = new Trend('loadam_op_latency', true);
const opStatus = new Counter('loadam_op_status');

function __statusBucket(s) {
  if (s < 200) return '1xx';
  if (s < 300) return '2xx';
  if (s < 400) return '3xx';
  if (s < 500) return '4xx';
  return '5xx';
}

const fixtures = new SharedArray('loadam-fixtures', function () {
  return [JSON.parse(open('./fixtures.json'))];
});

function pickFixture(opId, slot, idx) {
  const pool = fixtures[0][opId];
  if (!pool || !pool[slot]) return undefined;
  const arr = pool[slot];
  if (Array.isArray(arr)) return arr[idx % arr.length];
  return undefined;
}

function pickPathParam(opId, name, state, kind, idx) {
  if (kind && state[kind] && state[kind].length > 0) {
    return state[kind][state[kind].length - 1];
  }
  const pool = fixtures[0][opId];
  if (pool && pool.pathParams && pool.pathParams[name]) {
    const arr = pool.pathParams[name];
    return arr[idx % arr.length];
  }
  return undefined;
}

/**
 * Run one flow iteration. \`state\` accumulates created IDs by ResourceKind
 * so subsequent ops in the same iteration reuse them.
 */
export function runFlow(iter) {
  const state = {};
  const __ITER = iter || 0;
${lines.join("\n")}
}
`;
}

function emitOpCall(op: Operation, _index: number): string {
  const headersExpr = "Object.assign({}, authHeaders())";
  const opIdLit = JSON.stringify(op.id);

  const pathParamLines: string[] = [];
  let pathParamObj = "undefined";
  if (op.pathParams.length > 0) {
    const entries: string[] = [];
    for (const p of op.pathParams) {
      const ident = safeIdent(p.name);
      const kindLit = p.resourceKind ? JSON.stringify(p.resourceKind) : "undefined";
      pathParamLines.push(
        `    const __pp_${ident} = pickPathParam(${opIdLit}, ${JSON.stringify(p.name)}, state, ${kindLit}, __ITER);`,
      );
      entries.push(`${JSON.stringify(p.name)}: __pp_${ident}`);
    }
    pathParamObj = `{ ${entries.join(", ")} }`;
  }

  const requiredQuery = op.queryParams.filter((p) => p.required);
  let queryParamObj = "undefined";
  if (requiredQuery.length > 0) {
    const entries = requiredQuery
      .map(
        (p) =>
          `${JSON.stringify(p.name)}: (function () { const f = pickFixture(${opIdLit}, 'queryParams', __ITER); return f ? f[${JSON.stringify(p.name)}] : undefined; })()`,
      )
      .join(", ");
    queryParamObj = `{ ${entries} }`;
  }

  const requestLine = emitRequestCall(op, headersExpr, pathParamObj, queryParamObj);

  const captureId =
    op.resourceAction === "create" && op.resourceKind
      ? `    if (resp.status >= 200 && resp.status < 300) {
      let body;
      try { body = resp.json(); } catch (_) { body = undefined; }
      if (body && body.id !== undefined) {
        (state[${JSON.stringify(op.resourceKind)}] = state[${JSON.stringify(op.resourceKind)}] || []).push(body.id);
      }
    }`
      : "";

  return `  // ${op.method} ${op.path} — ${op.id}
  {
${pathParamLines.join("\n")}
    const resp = ${requestLine};
    check(resp, { ${JSON.stringify(`${op.id} 2xx-3xx`)}: (r) => r.status >= 200 && r.status < 400 });
    opLatency.add(resp.timings.duration, { name: ${opIdLit} });
    opStatus.add(1, { name: ${opIdLit}, bucket: __statusBucket(resp.status) });
${captureId}
  }
`;
}

function emitRequestCall(
  op: Operation,
  headersExpr: string,
  pathParamObj: string,
  queryParamObj: string,
): string {
  const url = `buildUrl(${JSON.stringify(op.path)}, ${pathParamObj}, ${queryParamObj})`;
  const method = op.method.toLowerCase();
  const hasBody = !!op.body;
  const opIdLit = JSON.stringify(op.id);

  const bodyExpr = hasBody ? `JSON.stringify(pickFixture(${opIdLit}, 'bodies', __ITER))` : "null";
  const headersWithCT = hasBody
    ? `Object.assign(${headersExpr}, { 'Content-Type': 'application/json' })`
    : headersExpr;

  if (method === "get" || method === "head" || method === "options") {
    return `http.${method}(${url}, { headers: ${headersExpr}, tags: { name: ${opIdLit} } })`;
  }
  if (method === "delete") {
    return `http.del(${url}, null, { headers: ${headersExpr}, tags: { name: ${opIdLit} } })`;
  }
  return `http.${method}(${url}, ${bodyExpr}, { headers: ${headersWithCT}, tags: { name: ${opIdLit} } })`;
}

function safeIdent(s: string): string {
  return s.replace(/[^A-Za-z0-9_]/g, "_");
}

export function emitSmokeJs(ctx: TemplateContext): string {
  return `// AUTO-GENERATED by @loadam/test-k6 — smoke test
import { runFlow } from './flow.js';

export const options = {
  vus: 1,
  iterations: 1,
  thresholds: {
    checks: ['rate>=0.95'],
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<2000'],
${emitOpThresholds(ctx)}  },
};

export default function () {
  runFlow(0);
}
`;
}

export function emitLoadJs(ctx: TemplateContext): string {
  return `// AUTO-GENERATED by @loadam/test-k6 — load test
import { runFlow } from './flow.js';

export const options = {
  stages: [
    { duration: '15s', target: 5 },
    { duration: '45s', target: 10 },
    { duration: '15s', target: 0 },
  ],
  thresholds: {
    checks: ['rate>=0.95'],
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<1000'],
${emitOpThresholds(ctx)}  },
};

export default function () {
  runFlow(__ITER);
}
`;
}

/**
 * Emit "sentinel" thresholds that always pass but force k6 to surface
 * per-operation sub-metrics in the summary export. Without these we
 * cannot show per-endpoint p95 latency or status-code distribution.
 */
function emitOpThresholds(ctx: TemplateContext): string {
  const buckets = ["1xx", "2xx", "3xx", "4xx", "5xx"];
  const lines: string[] = [];
  for (const op of ctx.sequencedOps) {
    lines.push(`    'loadam_op_latency{name:${op.id}}': ['p(95)<999999'],`);
    for (const b of buckets) {
      lines.push(`    'loadam_op_status{name:${op.id},bucket:${b}}': ['count>=0'],`);
    }
  }
  return lines.length === 0 ? "" : `${lines.join("\n")}\n`;
}

export function emitFixturesJson(pool: unknown): string {
  return `${JSON.stringify(pool, null, 2)}\n`;
}

export function emitPackageJson(ctx: TemplateContext): string {
  const name = slugify(ctx.ir.meta.title) || "loadam-k6";
  return `${JSON.stringify(
    {
      name: `${name}-k6`,
      version: "0.0.0",
      description: `k6 test rig for ${ctx.ir.meta.title} — generated by loadam`,
      private: true,
      scripts: {
        smoke: "k6 run smoke.js",
        load: "k6 run load.js",
      },
    },
    null,
    2,
  )}\n`;
}

export function emitEnvExample(ctx: TemplateContext): string {
  const lines = [
    "# Generated by loadam — copy to .env and fill in.",
    `BASE_URL=${ctx.baseUrl}`,
    "",
  ];
  for (const v of ctx.auth.envVars) lines.push(`${v}=`);
  return `${lines.join("\n")}\n`;
}

export function emitReadme(ctx: TemplateContext): string {
  const opCount = ctx.sequencedOps.length;
  const notes = ctx.auth.notes.length
    ? `\n## Auth notes\n\n${ctx.auth.notes.map((n) => `- ${n}`).join("\n")}\n`
    : "";
  return `# ${ctx.ir.meta.title} — k6 test rig

Generated by [loadam](https://github.com/loadam) from your API spec.

## Run

\`\`\`bash
# 1. fill credentials
cp .env.example .env

# 2. smoke test (1 VU, 1 iteration)
k6 run smoke.js

# 3. load test (ramps to 10 VUs over 75s)
k6 run load.js
\`\`\`

## What's in here

- \`smoke.js\` — runs each of the ${opCount} operations once, threading IDs from create→read→delete.
- \`load.js\` — same flow under ramping load with SLO thresholds.
- \`flow.js\` — shared per-iteration flow used by both scripts.
- \`fixtures.json\` — pre-generated request bodies and path-param values (k6 cannot run npm modules).
- \`config.js\` — base URL + auth header builder.
${notes}
## Regenerating

Re-run \`loadam test\` to refresh. Edits to generated files will be overwritten —
preserve-user-block markers land in V1.1.
`;
}

export function defaultBaseUrlFor(ir: IR): string {
  return defaultBaseUrl(ir);
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
