import type { IR } from "@loadam/core";
import type { McpAuth } from "./auth.js";
import type { ToolDef } from "./curate.js";

export interface TemplateContext {
  ir: IR;
  baseUrl: string;
  tools: ToolDef[];
  auth: McpAuth;
  includeWrites: boolean;
  sdkVersion: string;
}

/**
 * The emitted server is plain ESM JavaScript — no build step required by the
 * end user. They run `npm install && node bin.js` (or wire bin.js to Claude
 * Desktop's stdio config). Pin SDK version exactly so behaviour is stable.
 *
 * Files:
 *   package.json — bin entry + SDK dep
 *   bin.js       — argv parsing + transport selection
 *   server.js    — McpServer build + tool routing (low-level Server API)
 *   tools.js     — TOOLS array (data-only)
 *   client.js    — fetch wrapper that calls the upstream API
 *   auth.js      — env → headers/query
 *   .env.example
 *   README.md
 */

export function emitPackageJson(ctx: TemplateContext): string {
  const name = slugify(ctx.ir.meta.title) || "loadam-mcp";
  return `${JSON.stringify(
    {
      name: `${name}-mcp`,
      version: "0.0.0",
      description: `MCP server for ${ctx.ir.meta.title} — generated by loadam`,
      private: true,
      type: "module",
      bin: {
        [`${name}-mcp`]: "./bin.js",
      },
      scripts: {
        start: "node bin.js",
        "start:http": "node bin.js --http",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": ctx.sdkVersion,
      },
      engines: {
        node: ">=20",
      },
    },
    null,
    2,
  )}\n`;
}

export function emitBinJs(_ctx: TemplateContext): string {
  return `#!/usr/bin/env node
// AUTO-GENERATED by @loadam/mcp
import { buildServer } from './server.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';

function parseArgs(argv) {
  const args = { http: false, port: 3333, host: '127.0.0.1' };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--http') args.http = true;
    else if (a === '--port') args.port = Number(argv[++i]);
    else if (a === '--host') args.host = String(argv[++i]);
    else if (a === '--help' || a === '-h') {
      process.stdout.write(\`Usage: <bin> [--http] [--port N] [--host H]\\n\`);
      process.exit(0);
    }
  }
  return args;
}

async function main() {
  const args = parseArgs(process.argv);
  const server = buildServer();

  if (args.http) {
    const { StreamableHTTPServerTransport } = await import(
      '@modelcontextprotocol/sdk/server/streamableHttp.js'
    );
    const { createServer } = await import('node:http');
    const { randomUUID } = await import('node:crypto');

    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: () => randomUUID(),
    });
    await server.connect(transport);

    const http = createServer(async (req, res) => {
      try {
        await transport.handleRequest(req, res);
      } catch (err) {
        process.stderr.write(\`[mcp] http error: \${err && err.stack ? err.stack : err}\\n\`);
        if (!res.headersSent) {
          res.statusCode = 500;
          res.end();
        }
      }
    });
    http.listen(args.port, args.host, () => {
      process.stderr.write(\`[mcp] listening on http://\${args.host}:\${args.port}/mcp\\n\`);
    });
    return;
  }

  // Default: stdio transport — what Claude Desktop uses.
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write('[mcp] stdio ready\\n');
}

main().catch((err) => {
  process.stderr.write(\`[mcp] fatal: \${err && err.stack ? err.stack : err}\\n\`);
  process.exit(1);
});
`;
}

export function emitServerJs(ctx: TemplateContext): string {
  const name = slugify(ctx.ir.meta.title) || "loadam-mcp";
  return `// AUTO-GENERATED by @loadam/mcp
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { TOOLS } from './tools.js';
import { invokeTool } from './client.js';

export function buildServer() {
  const server = new Server(
    { name: ${JSON.stringify(`${name}-mcp`)}, version: '0.0.0' },
    { capabilities: { tools: {} } },
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: TOOLS.map((t) => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
    })),
  }));

  server.setRequestHandler(CallToolRequestSchema, async (req) => {
    const tool = TOOLS.find((t) => t.name === req.params.name);
    if (!tool) {
      return {
        isError: true,
        content: [
          { type: 'text', text: \`Unknown tool: \${req.params.name}\` },
        ],
      };
    }
    try {
      const result = await invokeTool(tool, req.params.arguments || {});
      return {
        content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
      };
    } catch (err) {
      const msg = err && err.message ? err.message : String(err);
      return {
        isError: true,
        content: [{ type: 'text', text: \`Error: \${msg}\` }],
      };
    }
  });

  return server;
}
`;
}

export function emitToolsJs(ctx: TemplateContext): string {
  const entries = ctx.tools
    .map(
      (t) =>
        `  ${JSON.stringify(
          {
            name: t.name,
            description: t.description,
            inputSchema: t.inputSchema,
            operation: t.operation,
          },
          null,
          2,
        )
          .split("\n")
          .map((line, i) => (i === 0 ? line : `  ${line}`))
          .join("\n")}`,
    )
    .join(",\n");
  return `// AUTO-GENERATED by @loadam/mcp
export const TOOLS = [
${entries}
];
`;
}

export function emitAuthJs(ctx: TemplateContext): string {
  const headerEntries = Object.entries(ctx.auth.headers);
  const queryEntries = Object.entries(ctx.auth.query);

  const headerLines = headerEntries.length
    ? headerEntries.map(([k, v]) => `  ${buildHeaderLine(k, v)}`).join("\n")
    : "  // no auth headers";

  const queryLines = queryEntries.length
    ? queryEntries.map(([k, v]) => `    ${JSON.stringify(k)}: ${interpolate(v)},`).join("\n")
    : "";

  return `// AUTO-GENERATED by @loadam/mcp
export function authHeaders() {
  const h = {};
${headerLines}
  return h;
}

export function authQuery() {
  return {
${queryLines}
  };
}
`;
}

function buildHeaderLine(name: string, value: string): string {
  if (value.startsWith("__BASIC__:")) {
    const [, userEnv, passEnv] = value.split(":");
    return `if (process.env.${userEnv} && process.env.${passEnv}) { h.Authorization = 'Basic ' + Buffer.from(process.env.${userEnv} + ':' + process.env.${passEnv}).toString('base64'); }`;
  }
  return `h[${JSON.stringify(name)}] = ${interpolate(value)};`;
}

function interpolate(value: string): string {
  // Translate "${ENV}" → JS template `${process.env.ENV || ''}` form.
  const replaced = value.replace(
    /\$\{([A-Z0-9_]+)\}/g,
    (_m, name) => `\${process.env.${name} || ''}`,
  );
  return `\`${replaced}\``;
}

export function emitClientJs(ctx: TemplateContext): string {
  return `// AUTO-GENERATED by @loadam/mcp
import { authHeaders, authQuery } from './auth.js';

const BASE_URL = process.env.BASE_URL || ${JSON.stringify(ctx.baseUrl)};

const PATH_PARAM_RE = /\\{([^}]+)\\}/g;

export async function invokeTool(tool, args) {
  const op = tool.operation;
  const headers = Object.assign({}, authHeaders());

  // Build URL: substitute path params, append query.
  let path = op.path;
  for (const name of op.pathParamNames) {
    const v = args[name];
    if (v === undefined || v === null) {
      throw new Error(\`Missing required path param "\${name}" for tool "\${tool.name}"\`);
    }
    path = path.split('{' + name + '}').join(encodeURIComponent(String(v)));
  }
  // Defensive: any unsubstituted "{...}" placeholders become an explicit error.
  const unresolved = path.match(PATH_PARAM_RE);
  if (unresolved) {
    throw new Error(\`Unresolved path placeholders: \${unresolved.join(', ')}\`);
  }

  const merged = Object.assign({}, authQuery());
  for (const name of op.queryParamNames) {
    if (args[name] !== undefined && args[name] !== null) merged[name] = args[name];
  }
  const qs = Object.keys(merged)
    .filter((k) => merged[k] !== undefined && merged[k] !== null && merged[k] !== '')
    .map((k) => encodeURIComponent(k) + '=' + encodeURIComponent(String(merged[k])))
    .join('&');

  const url = BASE_URL + path + (qs ? '?' + qs : '');

  for (const name of op.headerParamNames) {
    if (args[name] !== undefined && args[name] !== null) {
      headers[name] = String(args[name]);
    }
  }

  let body;
  if (op.hasBody && args.body !== undefined) {
    headers['Content-Type'] = 'application/json';
    body = JSON.stringify(args.body);
  }

  const resp = await fetch(url, { method: op.method, headers, body });
  const text = await resp.text();
  let parsed;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch (_) {
    parsed = text;
  }
  return {
    status: resp.status,
    headers: Object.fromEntries(resp.headers.entries()),
    body: parsed,
  };
}
`;
}

export function emitEnvExample(ctx: TemplateContext): string {
  const lines = [
    "# Generated by loadam — copy to .env or export in your shell.",
    `BASE_URL=${ctx.baseUrl}`,
    "",
  ];
  for (const v of ctx.auth.envVars) lines.push(`${v}=`);
  return `${lines.join("\n")}\n`;
}

export function emitReadme(ctx: TemplateContext): string {
  const toolList = ctx.tools.map((t) => `- \`${t.name}\` — ${t.description}`).join("\n");
  const writesNote = ctx.includeWrites
    ? "This server was generated with `--writes`, so it includes mutating operations (POST/PUT/PATCH/DELETE). Audit before connecting it to a writable backend."
    : "This server is **read-only by default** — it only exposes safe HTTP methods. Re-run `loadam mcp <spec> --writes` to include mutating ops.";
  const authNotes = ctx.auth.notes.length
    ? `\n## Auth notes\n\n${ctx.auth.notes.map((n) => `- ${n}`).join("\n")}\n`
    : "";
  return `# ${ctx.ir.meta.title} — MCP server

Generated by [loadam](https://github.com/loadam) from your API spec.

${writesNote}

## Run

\`\`\`bash
npm install

# stdio (Claude Desktop, Cursor, etc.)
node bin.js

# Streamable HTTP transport
node bin.js --http --port 3333
\`\`\`

## Connect to Claude Desktop

Add to \`~/Library/Application Support/Claude/claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "${slugify(ctx.ir.meta.title) || "loadam-mcp"}": {
      "command": "node",
      "args": ["${"<absolute path to this directory>"}/bin.js"],
      "env": {
        "BASE_URL": "${ctx.baseUrl}"${ctx.auth.envVars.length ? "," : ""}
${ctx.auth.envVars.map((v) => `        "${v}": "<value>"`).join(",\n")}
      }
    }
  }
}
\`\`\`

## Tools (${ctx.tools.length})

${toolList || "_No tools exposed — try regenerating with `--writes`._"}
${authNotes}
## Regenerating

Re-run \`loadam mcp <spec>\` to refresh. Edits to generated files will be overwritten.
`;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
